"""Tests for detectors/cache_instability.py — detect_cache_instability."""

import sys
import os
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "skills", "token-optimizer", "scripts"))

from detectors.cache_instability import detect_cache_instability


def _make_session(content):
    return {"claude_md_content": content}


def _big_block(n_lines=200):
    """Return a multi-line stable block of prose (no timestamps, no markers)."""
    return "\n".join(f"Rule {i}: do not do the bad thing and always do the good thing." for i in range(n_lines))


class CacheInstabilityTimestampTests(unittest.TestCase):

    def test_iso_datetime_in_prefix_triggers_finding(self):
        content = "# Config\nUpdated at 2026-06-22T14:30 UTC\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        names = [f["name"] for f in findings]
        self.assertIn("cache_instability", names)

    def test_day_month_date_in_prefix_triggers_finding(self):
        content = "# Notes\nMon, June 22\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_updated_label_date_in_prefix_triggers_finding(self):
        content = "# My Config\nUpdated: 2026-06-20\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_last_updated_in_prefix_triggers_finding(self):
        content = "# My Config\nLast updated: 2026-06-01\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_timestamp_only_in_suffix_no_finding(self):
        # Timestamp in the last 40% → should NOT trigger
        suffix_line = "Updated at 2026-06-22T14:30 UTC"
        stable_block = _big_block(200)
        content = stable_block + "\n" + suffix_line
        findings = detect_cache_instability(_make_session(content))
        self.assertEqual(findings, [])

    def test_finding_includes_savings_tokens_and_occurrence_count(self):
        content = "Updated: 2026-06-01\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        ts_findings = [f for f in findings if "cache_instability" == f["name"]]
        self.assertTrue(ts_findings)
        f = ts_findings[0]
        self.assertGreater(f["savings_tokens"], 0)
        self.assertGreaterEqual(f["occurrence_count"], 1)
        self.assertGreater(f["confidence"], 0)


class CacheInstabilityDynamicSectionTests(unittest.TestCase):

    def test_auto_generated_marker_in_prefix_triggers_finding(self):
        content = "# Config\n<!-- AUTO-GENERATED -->\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_do_not_edit_marker_in_prefix_triggers_finding(self):
        content = "# Config\n# DO NOT EDIT\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_generated_by_marker_in_prefix_triggers_finding(self):
        content = "# Config\nGenerated by some-tool\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_token_optimizer_marker_in_prefix_triggers_finding(self):
        content = "# Config\n# TOKEN_OPTIMIZER:MODEL_ROUTING\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))


class CacheInstabilityVolatileImportTests(unittest.TestCase):

    def test_volatile_import_path_triggers_finding(self):
        content = "@import 'status-report.md'\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_import_with_log_in_name_triggers_finding(self):
        content = '@import "daily-log.md"\n' + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        self.assertTrue(any(f["name"] == "cache_instability" for f in findings))

    def test_stable_import_path_does_not_trigger(self):
        content = "@import 'conventions.md'\n" + _big_block(150)
        findings = detect_cache_instability(_make_session(content))
        import_findings = [f for f in findings if "import" in f.get("evidence", "").lower()]
        self.assertEqual(import_findings, [])


class CacheInstabilityShortCircuitTests(unittest.TestCase):

    def test_empty_content_returns_no_findings(self):
        self.assertEqual(detect_cache_instability(_make_session("")), [])

    def test_short_content_under_200_chars_returns_no_findings(self):
        self.assertEqual(detect_cache_instability(_make_session("# tiny")), [])

    def test_missing_claude_md_key_returns_no_findings(self):
        self.assertEqual(detect_cache_instability({}), [])

    def test_stable_config_no_timestamps_no_findings(self):
        content = _big_block(200)
        self.assertEqual(detect_cache_instability(_make_session(content)), [])


if __name__ == "__main__":
    unittest.main()
